name 'opsworks-cookbooks-wrapper'
maintainer 'Ethan Dave B. Gomez'
maintainer_email 'ethan@elitechance.com'
license 'all_rights'
description 'Installs/Configures opsworks-cookbooks-wrapper'
long_description 'Installs/Configures opsworks-cookbooks-wrapper'
version '0.1.0'

depends 'opsworks_initial_setup'
depends 'ssh_host_keys'
depends 'ssh_users'
depends 'mysql'
depends 'dependencies'
depends 'ebs'
depends 'opsworks_ganglia'
depends 'opsworks_nodejs'
depends 'agent_version'
depends 'deploy'
